import type { GitFileStatus } from "./generated/git";
import type {
  NetworkStatusEventDto,
  TerminalExitEventDto,
  TerminalOutputEventDto,
} from "./generated/ipc";
export type {
  AclEntry,
  ByteDifferenceDto,
  CompareFilesRequest,
  CompareFilesResponse,
  ComputeHashRequest,
  ComputeHashResponse,
  DiffHunk,
  DiffHunkDto,
  DiffLine,
  DiffLineDto,
  DiffTextRequest,
  DiffTextResponse,
  DiscoverVolumesResponse,
  EjectVolumeRequest,
  EjectVolumeResponse,
  ExifMetadataDto,
  ExifTagDto,
  FolderSizeCompletedEventDto,
  FolderSizeJobResponse,
  FolderSizeRequest,
  FolderSizeResponse,
  FolderSizeSummaryDto,
  GetAclRequest,
  GetAclResponse,
  GitBranchDto,
  GitBranchesRequest,
  GitBranchesResponse,
  GitChangedFileDto,
  GitCommitDto,
  GitDiffFileRequest,
  GitDiffFileResponse,
  GitDiscoverRequest,
  GitDiscoverResponse,
  GitHistoryRequest,
  GitHistoryResponse,
  GitRepoInfoDto,
  GitRevisionDiffRequest,
  GitRevisionDiffResponse,
  GitRevisionFileDto,
  GitRevisionFilesRequest,
  GitRevisionFilesResponse,
  GitStatusForDirectoryRequest,
  GitStatusForDirectoryResponse,
  GitStatusForRepositoryRequest,
  GitStatusForRepositoryResponse,
  GitWorktreeDto,
  GitWorktreesRequest,
  GitWorktreesResponse,
  OkResponse,
  PathPropertiesDto,
  PathPropertiesRequest,
  PathPropertiesResponse,
  PathRequest,
  ReadFileAsDataUriRequest,
  ReadFileAsDataUriResponse,
  ReadFileRangeRequest,
  ReadFileRangeResponse,
  ReadImageAsDataUriRequest,
  ReadImageAsDataUriResponse,
  ReadTextFileRequest,
  ReadTextFileResponse,
  RecursiveSearchCompletedEventDto,
  RecursiveSearchJobResponse,
  RecursiveSearchMatchEventDto,
  RecursiveSearchRequest,
  RecursiveSearchResponse,
  RecursiveSearchResultDto,
  SearchMatchDto,
  SetAclRequest,
  SetAclResponse,
  StandardLocationDto,
  StandardLocationsResponse,
  StatRequest,
  StatResponse,
  SyncDirectoriesRequest,
  SyncDirectoriesResponse,
  SyncEntryDto,
  VolumeDto,
  WriteTextFileRequest,
  WriteTextFileResponse,
} from "./generated/ipc";
export type { GitFileStatus } from "./generated/git";

export type {
  AppInfoResponse,
  AppDataHealthResponse,
  AutostartStatusDto,
  BatchRenameItemDto,
  CancelJobRequest,
  ClearOperationHistoryResponse,
  ContentSearchCompletedEventDto,
  ContentSearchJobResponse,
  ContentSearchMatchDto,
  ContentSearchMatchEventDto,
  ContentSearchRequest,
  ContentSearchResponse,
  ContentSearchResultDto,
  DirectoryBatchEventDto,
  DirectoryEntryDto,
  ExportDiagnosticsBundleRequest,
  ExportDiagnosticsBundleResponse,
  FavoriteEntryDto,
  FileEntryDto,
  FileOperationConflictDto,
  FileOperationItemDto,
  FileOperationPlanDto,
  FileOperationRequestDto,
  FileOperationWarningDto,
  GetPreferencesResponse,
  InstalledPluginDto,
  JobStatusRequest,
  JobStatusResponse,
  ListArchiveRequest,
  ListArchiveResponse,
  ListDirectoriesRequest,
  ListDirectoriesResponse,
  ListRecentOperationsRequest,
  ListRecentOperationsResponse,
  ListStartRequest,
  ListStartResponse,
  LogRecordDto,
  NativeMenuCommandEventDto,
  NavigationAddFavoriteRequest,
  NavigationFavoriteResponse,
  NavigationIsStarredRequest,
  NavigationIsStarredResponse,
  NavigationListFavoritesResponse,
  NavigationListRecentRequest,
  NavigationListRecentResponse,
  NavigationListStarredResponse,
  NavigationRecordVisitRequest,
  NavigationRemoveFavoriteRequest,
  NavigationRemoveRecentRequest,
  NavigationRenameFavoriteRequest,
  NavigationToggleStarredRequest,
  NavigationToggleStarredResponse,
  NetworkConnectionStatusDto,
  NetworkConnectionStatusResponse,
  NetworkEnvVarDto,
  NetworkNeighborhoodRequest,
  NetworkNeighborhoodResponse,
  NetworkProfileActionRequest,
  NetworkProfileAddRequest,
  NetworkProfileDeleteRequest,
  NetworkProfileDraftDto,
  NetworkProfileDto,
  NetworkProfileResponse,
  NetworkProfilesListResponse,
  NetworkProfileSetSecretRequest,
  NetworkProfileTestRequest,
  NetworkProfileTestResponse,
  NetworkProfileTrustFingerprintRequest,
  NetworkProfileUpdateRequest,
  NetworkProtocolOptionsDto,
  NetworkProviderCapabilityDto,
  NetworkProvidersListResponse,
  NetworkStatusEventDto,
  OpenTerminalRequest,
  OpenTerminalResponse,
  OperationHistoryRecordDto,
  PauseJobRequest,
  PlanFileOperationRequest,
  PlanFileOperationResponse,
  PluginInstallRequest,
  PluginInstallResponse,
  PluginListResponse,
  PluginManifestDto,
  PluginToggleRequest,
  PluginToggleResponse,
  PluginUninstallRequest,
  RecentEntryDto,
  ResumeJobRequest,
  S3ProtocolOptionsDto,
  SetPreferenceRequest,
  SetPreferenceResponse,
  SmbProtocolOptionsDto,
  SshProtocolOptionsDto,
  StarredEntryDto,
  StartFileOperationRequest,
  StartFileOperationResponse,
  TerminalCapabilitiesResponse,
  TerminalEnvVarDto,
  TerminalExitEventDto,
  TerminalKillRequest,
  TerminalOkResponse,
  TerminalOutputEventDto,
  TerminalProfileActionRequest,
  TerminalProfileAddRequest,
  TerminalProfileDto,
  TerminalProfileInputDto,
  TerminalProfileResponse,
  TerminalProfilesListResponse,
  TerminalProfileScopeDto,
  TerminalProfileUpdateRequest,
  TerminalResizeRequest,
  TerminalRunCommandRequest,
  TerminalSendTextRequest,
  TerminalSessionDto,
  TerminalSessionEventDto,
  TerminalSessionsListResponse,
  TerminalSessionStatusDto,
  TerminalSpawnAndRunRequest,
  TerminalSpawnRequest,
  TerminalSpawnResponse,
  TerminalWriteRequest,
  UserPreferencesDto,
  WatchEventDto,
  WatchStartRequest,
} from "./generated/ipc";
export type {
  JobCancelledEvent,
  JobCompletedEvent,
  JobFailedEvent,
  JobPausedEvent,
  JobProgressEvent,
  JobResumedEvent,
  JobSnapshot,
  JobStartedEvent,
  JobStatus,
} from "./generated/jobs";
export type {
  ConflictPolicy,
  FileKind,
  FileOperationKind,
} from "./generated/vfs";

export type NetworkStatusEvent = NetworkStatusEventDto;
export type TerminalExitEvent = TerminalExitEventDto;
export type TerminalOutputEvent = TerminalOutputEventDto;
export type GitFileStatusDto = GitFileStatus;

export const IPC_ERROR_CODES = {
  INVALID_URI: "invalid_uri",
  UNSUPPORTED_PROVIDER: "unsupported_provider",
  DUPLICATE_PROVIDER: "duplicate_provider",
  NOT_FOUND: "not_found",
  PERMISSION_DENIED: "permission_denied",
  CLOUD_UNAVAILABLE: "cloud_unavailable",
  TIMEOUT: "timeout",
  RUNTIME_BUSY: "runtime_busy",
  RESOURCE_LIMIT_EXCEEDED: "resource_limit_exceeded",
  PLAN_EXPIRED: "plan_expired",
  CANCELLED: "cancelled",
  PREFERENCES_ERROR: "preferences_error",
  INVALID_REQUEST: "invalid_request",
  INVALID_NAME: "invalid_name",
  INVALID_PATH: "invalid_path",
  DESTINATION_MISSING: "destination_missing",
  DESTINATION_CONFLICT: "destination_conflict",
  RECURSIVE_OPERATION: "recursive_operation",
  UNSUPPORTED_SYMLINK: "unsupported_symlink",
  UNSUPPORTED_TRASH: "unsupported_trash",
  UNSUPPORTED_OPERATION: "unsupported_operation",
  IO_ERROR: "io_error",
  INTERNAL: "internal",
  IS_DIRECTORY: "is_directory",
  FILE_TOO_LARGE: "file_too_large",
  UNSUPPORTED_ALGORITHM: "unsupported_algorithm",
  SPAWN_ERROR: "spawn_error",
  NO_TERMINAL: "no_terminal",
  TERMINAL_SPAWN_FAILED: "terminal_spawn_failed",
  TERMINAL_NOT_FOUND: "terminal_not_found",
  INVALID_TERMINAL_SIZE: "invalid_terminal_size",
  TERMINAL_SESSION_EXITED: "terminal_session_exited",
  AUTOSTART_UNAVAILABLE: "autostart_unavailable",
  NETWORK_DISABLED: "network_disabled",
  NAVIGATION_ERROR: "navigation_error",
  NETWORK_ERROR: "network_error",
  CONNECTION_REQUIRED: "connection_required",
  AUTHENTICATION_FAILED: "authentication_failed",
  HOST_KEY_UNTRUSTED: "host_key_untrusted",
  HOST_KEY_MISMATCH: "host_key_mismatch",
  CONNECTION_LOST: "connection_lost",
  FOLDER_NOT_FOUND: "folder_not_found",
  GIT_COMMAND_FAILED: "git_command_failed",
  UNKNOWN: "unknown",
  TAURI_UNAVAILABLE: "tauri_unavailable",
  UNSUPPORTED_TRANSPORT: "unsupported_transport",
  DEVICE_UNAVAILABLE: "device_unavailable",
} as const;

export type KnownIpcErrorCode =
  (typeof IPC_ERROR_CODES)[keyof typeof IPC_ERROR_CODES];
export type IpcErrorCode = KnownIpcErrorCode | (string & {});

export const FILE_OPERATION_WARNING_CODES = {
  METADATA_FAILED: "metadata_failed",
} as const;

export type KnownFileOperationWarningCode =
  (typeof FILE_OPERATION_WARNING_CODES)[keyof typeof FILE_OPERATION_WARNING_CODES];
export type FileOperationWarningCode =
  KnownFileOperationWarningCode | (string & {});

export function isKnownIpcErrorCode(code: string): code is KnownIpcErrorCode {
  return Object.values(IPC_ERROR_CODES).includes(code as KnownIpcErrorCode);
}

export function isKnownFileOperationWarningCode(
  code: string,
): code is KnownFileOperationWarningCode {
  return Object.values(FILE_OPERATION_WARNING_CODES).includes(
    code as KnownFileOperationWarningCode,
  );
}

export interface IpcTransport {
  invoke<TResponse>(
    command: string,
    args?: Record<string, unknown>,
  ): Promise<TResponse>;
  listen?<TPayload>(
    event: string,
    handler: (payload: TPayload) => void,
  ): Promise<UnlistenFn>;
}

export type UnlistenFn = () => void;

export interface IpcError {
  code: IpcErrorCode;
  message: string;
}

export interface NetworkConnectionDraftDto {
  scheme?: string | null;
  host?: string | null;
  label?: string | null;
  defaultPath?: string | null;
}
